services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: tukanoUser
      POSTGRES_PASSWORD: tukanoPassword
      POSTGRES_DB: tukanoDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data: